[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[invariant]
runs = 1000000000
depth = 25
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config